# ============================================
#        CustomSpawners - config.yml
# ============================================

# Banco de dados
database:
  # Se estiver em false irá ativar o SQLite, caso estiver true irá ativar HikariCP
  enable: false
  data:
    host: '0.0.0.0'
    port: 3306
    username: 'root'
    password: 'root'
    database: 'minecraft'

# Intervalo em ticks que o engine verifica spawners prontos
engine-tick-interval: 1

# Range (em blocos) que o jogador precisa estar para ativar o spawner
activation-range: 16

# Salvar dados a cada X segundos (async)
auto-save-interval: 300

# Configuração geral dos spawners
spawners:
  # Delay minimo para gerar mobs
  min-delay: 200
  # Delay maximo para gerar mobs
  max-delay: 800
  # Quantidade de mobs que irão nascer por rodada
  spawn-count: 4


# ============================================
#   Stack de Mobs
# ============================================
stack-mobs:
  enable: true
  stack-radius: 5
  max-stack-size: 1000
  # {count} = quantidade | {mob} = nome do mob
  display-name: '&e{count}x &7{mob}'
  kill-all: true

# Debug (Este opção pode floodar se console)
debug: false

# Bloquear mobs nascerem de modo natural?
bloquear-mobs-nascerem: true
# Mundo onde os mobs não irão nascer!
mundo-mobs:
  - ''
# Region onde os mobs não irão nascer!
region-mobs:
  - ''